### PR TITLE
Added allowed domains and enable offilne options.

### PR DESCRIPTION
**Pull request by fizerkhan**
1. Support for user id, email and name in identify.
2. Please add two new options in the segment UI.

-  New option `enableOffline`

```
Label: Enable Offline
Description: Enable offline errors and metrics tracking when network connectivity is not available
```
- New option `allowedDomains`

```
Label:  Allowed Domains (Comma Separated)
Description:  Track errors and performance metrics only from specific domains.
```

3. Please remove the option `Enable Source Map`

### CODE REVIEW

**Comment by fizerkhan** [comment]
@f2prateek I have a problem in test. Could you please help me to fix it?

```
     Error: You must call `.spy(object, method)` prior to calling `.called()`.
```

**Comment by fizerkhan** [comment]
@f2prateek Could you please the merge the changes?

**Comment by Peripheral1994** [comment]
Hey @fizerkhan - Sorry for the delay on this, thanks so much for the PR! I'm looking into merging this very soon, I'll just have a couple edits to help mesh this better with our modern UI settings. Will post back once I've tested! :)

**Comment by fizerkhan** [comment]
@Peripheral1994 Thanks for the update.

**Comment by fizerkhan** [comment]
@Peripheral1994 This pull request is still waiting to merge. Could you please review and merge it?

**Comment by Peripheral1994** [comment]
Tests were good, merged in #12 - starting deployment now, so this should hopefully be out in an hour or two!

**Comment by fizerkhan** [comment]
@Peripheral1994 Thanks. It has been updated in Segment UI. But the documentation is not updated yet https://segment.com/docs/destinations/atatus/

**Comment by Peripheral1994** [comment]
Hey @fizerkhan - I think there might've been a delay in the documentation releasing; it looks fine now. Can you confirm? I'd like to make sure everyone's getting the options. :)

**Comment by fizerkhan** [comment]
@Peripheral1994 Thanks Peter. It looks great now. You are awesome 👍

**Pull request closed without merging**
