### PR TITLE
Added enable options(boolean)

### PR DESCRIPTION
**Pull request by fizerkhan**
We added advanced enable options to Atatus. Can you please merge it?

### CODE REVIEW

**Comment by f2prateek** [comment]
Missing corresponding tests.

**Comment by fizerkhan** [comment]
Updated test with options.

**Comment by ndhoule** [comment]
@fizerkhan Can you provide us with descriptions of what each option does, and link to the relevant Atatus documentation if possible?

**Comment by fizerkhan** [comment]
FInd the description as follows

#### enableSourcemap

**Title:** Enable Source Maps
**Tooltip:** A flag to determine whether to enable source maps to translate the minified code references back into the original source.

#### enableAjaxErrors

**Title:** Capture Ajax Errors 
**Tooltip:** A flag to determine whether to enable reporting of Ajax 400, 500 errors.

#### enableAjaxAbort

**Title:** Capture Ajax Abort Errors
**Tooltip:** A flag to determine whether to enable reporting of Ajax abort errors.

**Comment by sperand-io** [comment]
@ndhoule @f2prateek  I'm happy to make the updates to metadata with the above info^ otherwise does this look gtg?

@fizerkhan thanks so much!

**Comment by ndhoule** [comment]
lgtm. thanks, @fizerkhan!

**Comment by fizerkhan** [comment]
Thanks @ndhoule @sperand-io  @f2prateek

**Comment by fizerkhan** [comment]
@ndhoule @sperand-io From Segment Atatus integration page, it set as 

```
{
    "settings": {
        "apiKey": "8d53498145024c6dafed783eced31e12",
        "enableSourcemap": true,
        "reportAjaxAborts": true,
        "reportAjaxErrors": true
    },
    "enabled": true,
    "type": "Atatus"
}
```

There are two issues:
1. The field names are incorrect, it should be 

```
enableSourcemap: true
enableAjaxErrors: true
enableAjaxAbort: true
```
1. Even though field `enableSourcemap` is set as true in segment atatus integration page, i am still getting `false` in analytics.js options. I don't know why it is happening?

Can you resolve this issue?

**Comment by ndhoule** [comment]
@fizerkhan my fault, I renamed the fields to be more clear and missed a spot. Pushed out a fix, can you try again?

**Comment by fizerkhan** [comment]
@ndhoule The options are renamed incorrectly. Acceptable options in atatus script are 

```
enableSourcemap
enableAjaxErrors
enableAjaxAbort
```

Corrected options in pull request #3

**Pull request merged**
